### ISSUE TITLE
Original filename lost on upload

### ISSUE THREAD

**Issue by camjac251** [Poly-Development/PolyCloud#2]
Is this intended? Uploading files strips the filename in the file list and on saving files loaded from their URLs.

**Comment by Lethdev2019** [comment]
that is already in my to-do, but thanks for bringing it to my attention (it's an unfinished project)

**Comment by DankBoi293** [comment]
Well, what if two people upload an image called `example.png` or `index.html`, wouldn't that cause problems on the database?

**Comment by camjac251** [comment]
The filename on disk could be unique but in the database, you could have a separate field named original_filename that would be used for saving.

**Comment by Lethdev2019** [comment]
@camjac251 
Thanks for the solution. we've just been really busy.

I will set this to planned.
_New Contributor Riddle_:
>Which month has 28 days?

**Comment by Lethdev2019** [comment]
> Well, what if two people upload an image called `example.png`, wouldn't that cause problems on the database?

No. because of the USER row. the USER row specifies which user uploaded it.
The bit you should _really_ worry about is the disk overwriting _if_ the database crawled the filesystem and added them. However, it does not. Instead it writes the file to the database _during_ file uploads thanks to nodejs' native `async` function.

**Comment by DankBoi293** [comment]
Reopening after update
